name: attendance

services:
  postgres:
    restart: unless-stopped
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - postgres-data:/var/lib/postgresql/data
  attendance-system:
    restart: unless-stopped
    image: ghcr.io/team3132/attendance:${TAG:-latest}
    ports:
      - 1420:1420
    links:
      - postgres
    environment:
      - TZ=Australia/Sydney
      - DATABASE_URL
      - DISCORD_CLIENT_ID
      - DISCORD_CLIENT_SECRET
      - DISCORD_CALLBACK_URL
      - DISCORD_TOKEN
      - DISCORD_PUBLIC_KEY
      - GUILD_ID
      - VITE_URL
      - GOOGLE_CLIENT_EMAIL
      - GOOGLE_PRIVATE_KEY
      - GOOGLE_CALENDAR_ID
      - ADMIN_ROLE_ID

volumes:
  postgres-data:
